---
- name: Install and configure Apache web server
  hosts: web
  become: true
  gather_facts: true


  tasks:
        - name: Install Apache (Debian/Ubuntu)
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: true
      when: ansible_facts.os_family == "Debian"

    - name: Install Apache (RHEL-family)
      ansible.builtin.yum:
        name: httpd
        state: present
      when: ansible_facts.os_family == "RedHat"

    - name: Deploy index.html to the default web root
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        mode: "0644"
        content: |
          <!doctype html>
          <html>
            <head><meta charset="utf-8"><title>{{ site_title }}</title></head>
            <body style="font-family: Arial, sans-serif;">
              <h1>{{ site_title }}</h1>
              <p>{{ site_message }}</p>
              <hr>
              <p><strong>Host:</strong> {{ inventory_hostname }}</p>
            </body>
          </html>

    - name: Ensure Apache is running and enabled (Debian/Ubuntu)
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true
      when: ansible_facts.os_family == "Debian"

    - name: Ensure Apache is running and enabled (RHEL-family)
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
      when: ansible_facts.os_family == "RedHat"


    - name: Check if firewalld is installed
      ansible.builtin.package_facts:
        manager: auto

    - name: Open HTTP service in firewalld (if present)
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
      when:
        - ansible_facts.os_family == "RedHat"
        - "'firewalld' in ansible_facts.packages"
